update sonar self host value

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -39,41 +39,36 @@ jobs:
         node -v
         npm install
 
-    - name: SonarQube Scan
-      uses: SonarSource/sonarcloud-github-action@v2
-      with:
-        args: >
-          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
-          -Dsonar.projectName=${{ env.SONAR_PROJECT_NAME }}
-          -Dsonar.sources=.
+    - name: Run SonarQube Analysis (Self-Hosted)
+      uses: SonarSource/sonarqube-scan-action@v5
       env:
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: http://13.250.32.137:9000
 
-    - name: Wait for SonarQube Quality Gate
-      env:
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-        SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}
-      run: |
-        echo "Checking SonarQube Quality Gate status..."
-        status="PENDING"
-        timeout=300
-        interval=10
-        elapsed=0
-        while [[ "$status" == "PENDING" ]] && [[ $elapsed -lt $timeout ]]; do
-          sleep $interval
-          elapsed=$((elapsed + interval))
-          qualityGateStatus=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY" | jq -r '.projectStatus.status')
-          echo "Current status: $qualityGateStatus"
-          if [[ "$qualityGateStatus" != "PENDING" ]]; then
-            status=$qualityGateStatus
-          fi
-        done
-        if [[ "$status" != "OK" ]]; then
-          echo "Quality gate failed with status: $status"
-          exit 1
-        fi
+    # - name: Wait for SonarQube Quality Gate
+    #   env:
+    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+    #     SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}
+    #   run: |
+    #     echo "Checking SonarQube Quality Gate status..."
+    #     status="PENDING"
+    #     timeout=300
+    #     interval=10
+    #     elapsed=0
+    #     while [[ "$status" == "PENDING" ]] && [[ $elapsed -lt $timeout ]]; do
+    #       sleep $interval
+    #       elapsed=$((elapsed + interval))
+    #       qualityGateStatus=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY" | jq -r '.projectStatus.status')
+    #       echo "Current status: $qualityGateStatus"
+    #       if [[ "$qualityGateStatus" != "PENDING" ]]; then
+    #         status=$qualityGateStatus
+    #       fi
+    #     done
+    #     if [[ "$status" != "OK" ]]; then
+    #       echo "Quality gate failed with status: $status"
+    #       exit 1
+    #     fi
     
     - name: Run Trivy File System Scan
       uses: aquasecurity/trivy-action@master
